syscall: adapt sys_spawn to ch6
os/syscall.c: In function 'sys_spawn':
os/syscall.c:188:7: error: implicit declaration of function 'get_id_by_name' [-Werror=implicit-function-declaration]
  188 |  id = get_id_by_name(name);
      |       ^~~~~~~~~~~~~~
os/syscall.c:197:6: error: implicit declaration of function 'loader'; did you mean 'bin_loader'? [-Werror=implicit-function-declaration]
  197 |  if (loader(id, np) < 0) {
      |      ^~~~~~
      |      bin_loader

This commit refactors the sys_spawn system call to make it compatible with the new
filesystem-based program loading mechanism introduced in ch6.

The previous implementation of spawn was designed for the ch5 architecture, where applications
were loaded from a pre-compiled, in-memory archive using an internal ID. With the transition to
a proper on-disk filesystem, this loading method became obsolete, causing the spawn system call to fail.

It now accepts a file path string from the user, uses namei() to resolve this path to
its corresponding inode on the disk. If the file is found, it allocates a new process
and uses the bin_loader() function to load the executable content from the inode into
the new process's address space. Otherwise, use init_stdio() to initialize standard I/O
for the new process to avoid errors like "[ERROR <pid>]invalid fd 1" because of
p->files[fd], that which files[1] is null. This change fully integrates spawn with the
filesystem, allowing it to correctly load and execute programs from disk.

Signed-off-by: 0wnerDied <z1281552865@gmail.com>